#pragma once

enum keyboard_layer {
    // Base layers
    _QWERTY,
    _LAYER_CHOOSER,
    _GAMES,
    _IMPACT,
    _WOW,
    _VALHEIM
};

enum {
    TD_LAYER_FN,
    TD_ESC_ZERO,
    TD_ATK_ALL,
    TD_1_ALT_1,
    TD_2_ALT_2,
    TD_3_ALT_3,
    TD_4_ALT_4,
    TD_5_ALT_5,
    TD_6_ALT_6,
    TD_7_ALT_7,
    TD_8_ALT_8,
    TD_9_ALT_9,
    TD_0_ALT_0,
    TD_1_S_1,
    TD_2_S_2,
    TD_3_S_3,
    TD_4_S_4,
    TD_5_S_5,
    TD_F1_S_F1,
    TD_F2_S_F2,
    TD_F3_S_F3,
    TD_F4_S_F4,
    TD_F5_S_F5,
    TD_F6_S_F6,
    TD_F7_S_F7,
    TD_F8_S_F8,
    TD_F9_S_F9,
    TD_F10_S_F10,
    TD_F11_S_F11,
    TD_F12_S_F12,
    TD_INS_S_INS,
    TD_DEL_S_DEL,
    TD_HOME_S_HOME,
    TD_END_S_END,
    TD_PGUP_S_PGUP,
    TD_PGDN_S_PGDN,
    TD_T_OR_X,
    TD_1_N_ALT_1,
    TD_2_N_ALT_2,
    TD_3_N_ALT_3,
    TD_4_N_ALT_4,
    TD_5_N_ALT_5,
    TD_6_N_ALT_6,
    TD_7_N_ALT_7,
    TD_8_N_ALT_8,
    TD_1_5,
    TD_2_6,
    TD_3_7,
    TD_4_8,
    TD_5_9,
    TD_Z_A1,
    TD_V_A2,
    TD_B_A3
};
